### ISSUE TITLE
OSError:no matching service when running svart

### ISSUE THREAD

**Issue by neotaruntius** [sdushantha/svart#2] opened 2021-04-09 08:42 UTC
# svart
Traceback (most recent call last):
  File "/Users/xxx/Library/Python/3.8/bin/svart", line 5, in <module>
    from svart.svart import main
  File "/Users/xxxx/Library/Python/3.8/lib/python/site-packages/svart/__init__.py", line 1, in <module>
    from .svart import main
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/svart/svart.py", line 10, in <module>
    import als
OSError: no matching service

**Comment by sdushantha** [comment] 2021-04-09 08:45
Closing this because it's a duplicate of #1

**Closed as completed by sdushantha** 2021-04-09 08:45 UTC
Labels: duplicate
